import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const seedDirectory = join(projectRoot, "db", "seeds");
const seedTimestamp = "2026-09-11T00:00:00.000Z";
const seedActor = "seed:portfolio-v1";

const bundle = await build({
  absWorkingDir: projectRoot,
  entryPoints: ["app/portfolio/data.ts"],
  bundle: true,
  write: false,
  platform: "node",
  format: "cjs",
  target: "node22",
});
const module = { exports: {} };
new Function("module", "exports", "require", bundle.outputFiles[0].text)(module, module.exports, () => {
  throw new Error("The portfolio data bundle must not load runtime dependencies.");
});
const { portfolioProjects } = module.exports;

const mimeByExtension = { ".webp": "image/webp", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".svg": "image/svg+xml" };
const slugify = value => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
  .replace(/đ/g, "d").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const normalizeSearchText = value => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
  .replace(/đ/gi, "d").toLowerCase().trim();
const quote = value => `'${String(value).replaceAll("'", "''")}'`;
const sqlValue = value => value === null ? "NULL" : typeof value === "number" ? String(value) : quote(value);
const json = value => JSON.stringify(value);

const mediaBySource = new Map();
const registerMedia = async media => {
  if (mediaBySource.has(media.src)) return mediaBySource.get(media.src);
  const relativePath = media.src.replace(/^\.\//, "");
  const filePath = join(projectRoot, relativePath);
  const fileName = basename(relativePath);
  const buffer = await readFile(filePath);
  const info = await stat(filePath);
  const asset = {
    id: `seed-media-${slugify(fileName.replace(extname(fileName), ""))}`,
    sourcePath: media.src,
    objectKey: `seed/original/${fileName}`,
    originalName: fileName,
    mime: mimeByExtension[extname(fileName).toLowerCase()] ?? "application/octet-stream",
    bytes: info.size,
    width: media.width,
    height: media.height,
    altDefault: media.alt,
    checksum: createHash("sha256").update(buffer).digest("hex"),
  };
  mediaBySource.set(media.src, asset);
  return asset;
};

const projects = [];
for (const [projectIndex, project] of portfolioProjects.entries()) {
  const thumbnail = await registerMedia(project.thumbnail);
  const cover = await registerMedia(project.cover);
  const isPlaceholder = project.status === "placeholder";
  const blocks = [];
  if (!isPlaceholder) {
    for (const section of project.sections) {
      blocks.push({ id: `${section.id}-eyebrow`, type: "text", paragraphs: [{ spans: [{ text: section.eyebrow, italic: true }] }] });
      blocks.push({ id: `${section.id}-heading`, type: "heading", level: 2, text: section.title });
      blocks.push({ id: `${section.id}-copy`, type: "text", paragraphs: [{ spans: [{ text: section.copy }] }] });
      if (section.media) {
        const asset = await registerMedia(section.media);
        blocks.push({ id: `${section.id}-media`, type: "image", assetId: asset.id, alt: section.media.alt, fit: section.media.fit ?? "contain" });
      }
    }
  }
  const document = { schemaVersion: 1, blocks };
  const metadata = {
    categoryId: project.primaryCategory,
    title: project.title,
    shortTitle: project.shortTitle,
    subtitle: project.summary,
    thumbnailAssetId: thumbnail.id,
    coverAssetId: cover.id,
    tags: project.tags,
    tools: project.tools,
    role: project.role,
    year: project.year,
    isFeatured: projectIndex === 0,
    sortOrder: project.order * 10,
  };
  const assetIds = [...new Set([thumbnail.id, cover.id, ...blocks.flatMap(block => block.type === "image" ? [block.assetId] : [])])];
  projects.push({
    id: project.id,
    legacyStatus: project.status,
    slug: slugify(project.title),
    metadata,
    document,
    contentState: blocks.length ? "ready" : "empty",
    revisionId: `seed-revision-${project.id}-v1`,
    assetIds,
  });
}

const manifest = {
  schemaVersion: 1,
  generatedFrom: "app/portfolio/data.ts",
  generatedAt: seedTimestamp,
  media: [...mediaBySource.values()],
  projects,
};

const statements = [
  "-- Generated by scripts/generate-db-seed.mjs. Do not edit by hand.",
  "PRAGMA foreign_keys = ON;",
  "BEGIN TRANSACTION;",
];
for (const asset of manifest.media) statements.push(
  `INSERT INTO media_assets (id, object_key, original_name, mime, bytes, width, height, alt_default, checksum, state, created_by, created_at) VALUES (${[
    asset.id, asset.objectKey, asset.originalName, asset.mime, asset.bytes, asset.width, asset.height, asset.altDefault,
    asset.checksum, "ready", seedActor, seedTimestamp,
  ].map(sqlValue).join(", ")}) ON CONFLICT(id) DO NOTHING;`,
);
for (const project of projects) {
  const metadataJson = json(project.metadata);
  const bodyJson = json(project.document);
  statements.push(
    `INSERT INTO projects (id, slug, draft_meta_json, draft_body_json, draft_version, created_at, updated_at) VALUES (${quote(project.id)}, ${quote(project.slug)}, ${quote(metadataJson)}, ${quote(bodyJson)}, 1, ${quote(seedTimestamp)}, ${quote(seedTimestamp)}) ON CONFLICT(id) DO NOTHING;`,
    `INSERT INTO project_revisions (id, project_id, source_version, meta_json, body_json, schema_version, created_by, created_at) VALUES (${quote(project.revisionId)}, ${quote(project.id)}, 1, ${quote(metadataJson)}, ${quote(bodyJson)}, 1, ${quote(seedActor)}, ${quote(seedTimestamp)}) ON CONFLICT(id) DO NOTHING;`,
  );
  for (const assetId of project.assetIds) {
    statements.push(
      `INSERT INTO revision_assets (revision_id, asset_id) VALUES (${quote(project.revisionId)}, ${quote(assetId)}) ON CONFLICT(revision_id, asset_id) DO NOTHING;`,
      `INSERT INTO draft_assets (project_id, asset_id) SELECT ${quote(project.id)}, ${quote(assetId)} WHERE EXISTS (SELECT 1 FROM projects WHERE id = ${quote(project.id)} AND draft_version = 1 AND updated_at = ${quote(seedTimestamp)}) ON CONFLICT(project_id, asset_id) DO NOTHING;`,
    );
  }
  const searchText = normalizeSearchText([project.metadata.title, project.metadata.shortTitle, project.metadata.subtitle, ...project.metadata.tags, ...project.metadata.tools].join(" "));
  statements.push(
    `INSERT INTO public_projects (project_id, revision_id, category_id, title, short_title, subtitle, thumbnail_asset_id, sort_order, is_featured, search_text, content_state, published_at) SELECT ${[
      project.id, project.revisionId, project.metadata.categoryId, project.metadata.title, project.metadata.shortTitle,
      project.metadata.subtitle, project.metadata.thumbnailAssetId, project.metadata.sortOrder, project.metadata.isFeatured ? 1 : 0,
      searchText, project.contentState, seedTimestamp,
    ].map(sqlValue).join(", ")} WHERE EXISTS (SELECT 1 FROM projects WHERE id = ${quote(project.id)} AND draft_version = 1 AND updated_at = ${quote(seedTimestamp)}) ON CONFLICT(project_id) DO NOTHING;`,
  );
}
statements.push("COMMIT;", "");

await mkdir(seedDirectory, { recursive: true });
await Promise.all([
  writeFile(join(seedDirectory, "portfolio-seed.json"), `${JSON.stringify(manifest, null, 2)}\n`),
  writeFile(join(seedDirectory, "portfolio-seed.sql"), statements.join("\n")),
]);
console.log(`Generated ${projects.length} projects and ${manifest.media.length} media records.`);
