const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
})[character]);

export function renderDocument(markup, site) {
  let base;
  if (site.siteUrl) {
    base = new URL(site.siteUrl);
    if (!/^https?:$/.test(base.protocol) || base.username || base.password || base.search || base.hash) {
      throw new Error("siteUrl must be an http(s) website URL without credentials, query or fragment.");
    }
    if (!base.pathname.endsWith("/")) base.pathname += "/";
  }
  const title = escapeHtml(site.title);
  const description = escapeHtml(site.description);
  const preview = escapeHtml(base ? new URL("public/og.png", base).href : "./public/og.png");
  return `<!doctype html>
<!-- Generated by npm run build. Edit app/ and site.config.mjs, not this file. -->
<html lang="${escapeHtml(site.lang)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <meta name="description" content="${description}">
  <link rel="icon" href="./public/caelestia-logo.svg" type="image/svg+xml">
  <link rel="stylesheet" href="./assets/app.css">
  <meta property="og:title" content="${title}">
  <meta property="og:description" content="${description}">
  <meta property="og:type" content="website">
  <meta property="og:image" content="${preview}">
  <meta property="og:image:width" content="1680">
  <meta property="og:image:height" content="945">
  <meta property="og:image:alt" content="Hieu Pham Caelestia Shell web replica">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${title}">
  <meta name="twitter:description" content="${description}">
  <meta name="twitter:image" content="${preview}">
  ${base ? `<link rel="canonical" href="${escapeHtml(base.href)}">\n  <meta property="og:url" content="${escapeHtml(base.href)}">` : ""}
  <script defer src="./assets/app.js"></script>
</head>
<body>
  <div id="root">${markup}</div>
  <noscript><p style="position:fixed;z-index:100;bottom:0;background:#fff;padding:12px">Enable JavaScript to use the interactive portfolio shell. The wallpaper remains available offline.</p></noscript>
</body>
</html>
`;
}
