import type { Filter, PortfolioProject } from "./types";

export const categoryLabels: Record<Filter, string> = {
  all: "All",
  photoshop: "Visual",
  illustrator: "Brand",
  blender: "3D",
  game: "Game",
  web: "Web",
  app: "App",
};

export const categoryDescriptions: Record<Filter, string> = {
  all: "Selected work across visual design, 3D and digital products.",
  photoshop: "Posters, retouching, compositing and campaign imagery.",
  illustrator: "Packaging, labels, logos and vector-led brand systems.",
  blender: "3D products, spatial concepts and exhibition environments.",
  game: "Interactive worlds, game systems and real-time experiences.",
  web: "Responsive interfaces and web products built for real workflows.",
  app: "Desktop and mobile tools that simplify operational work.",
};

const labelMedia = {
  src: "./public/vinut-coco-boba-label.webp",
  alt: "Vinut Coco Boba coconut milk tea label artwork and print production sheet",
  width: 741,
  height: 680,
  fit: "contain" as const,
};
const posterMedia = {
  src: "./public/coco-boba-poster.webp",
  alt: "Coco Boba Tini World campaign poster with a coconut milk tea can and miniature storefront",
  width: 484,
  height: 684,
  fit: "cover" as const,
};
const boothMedia = {
  src: "./public/nam-viet-group-booth.webp",
  alt: "Nam Viet Group exhibition booth concept with beverage displays and green branding",
  width: 553,
  height: 553,
  fit: "cover" as const,
};
const placeholderMedia = {
  src: "./public/portfolio-placeholder.svg",
  alt: "Temporary portfolio project placeholder",
  width: 640,
  height: 640,
  fit: "cover" as const,
};

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "vinut-coco-boba-label",
    title: "Vinut Coco Boba — Label System",
    shortTitle: "Coco Boba Label",
    summary: "A production-ready label system balancing a playful character world with dense export information.",
    primaryCategory: "illustrator",
    discipline: "design",
    tags: ["packaging", "label", "vector", "print", "coco boba", "vinut"],
    status: "published",
    order: 1,
    thumbnail: labelMedia,
    cover: labelMedia,
    role: "Packaging & label design",
    year: "Selected work",
    tools: ["Adobe Illustrator", "Print production"],
    sections: [
      {
        id: "visual-system",
        eyebrow: "01 / Visual system",
        title: "One label, many layers of information",
        copy: "The composition gives the character and Coco Boba name a clear center while nutritional, legal and production information remain organized around it.",
        media: labelMedia,
      },
      {
        id: "production",
        eyebrow: "02 / Production",
        title: "Prepared for real packaging work",
        copy: "Color channels, dimensions, print status and artwork variants are presented as part of the working file rather than hidden behind a decorative mockup.",
      },
    ],
  },
  {
    id: "coco-boba-tini-world",
    title: "Coco Boba — Tini World",
    shortTitle: "Tini World",
    summary: "A bright product campaign that turns the beverage can into the center of a miniature brand world.",
    primaryCategory: "photoshop",
    discipline: "design",
    tags: ["photoshop", "campaign", "poster", "compositing", "beverage", "coco boba"],
    status: "published",
    order: 2,
    thumbnail: posterMedia,
    cover: posterMedia,
    role: "Campaign visual & compositing",
    year: "2024",
    tools: ["Adobe Photoshop", "Art direction"],
    sections: [
      {
        id: "campaign-world",
        eyebrow: "01 / Campaign world",
        title: "A product large enough to become a place",
        copy: "The can anchors the scene while storefronts, characters and small details build a playful world around the product without losing brand recognition.",
        media: posterMedia,
      },
      {
        id: "hierarchy",
        eyebrow: "02 / Composition",
        title: "Fast recognition from top to bottom",
        copy: "Launch messaging leads into the hero can, then the eye lands on the product family and milk-tea proposition at the bottom of the poster.",
      },
    ],
  },
  {
    id: "nam-viet-exhibition",
    title: "Nam Viet Group — Exhibition Booth",
    shortTitle: "Exhibition Booth",
    summary: "A product-led exhibition environment designed to present a broad beverage portfolio from one clear viewpoint.",
    primaryCategory: "blender",
    discipline: "design",
    tags: ["3d", "blender", "booth", "exhibition", "beverage", "nam viet"],
    status: "published",
    order: 3,
    thumbnail: boothMedia,
    cover: boothMedia,
    role: "Exhibition environment",
    year: "Selected work",
    tools: ["3D visualization", "Spatial design"],
    sections: [
      {
        id: "space",
        eyebrow: "01 / Environment",
        title: "A compact stage for a large product family",
        copy: "The booth uses a strong green-and-white silhouette, illuminated product walls and a clear central counter to stay recognizable across a busy exhibition floor.",
        media: boothMedia,
      },
      {
        id: "navigation",
        eyebrow: "02 / Visitor flow",
        title: "Products remain visible from the aisle",
        copy: "Large campaign graphics establish the brand at a distance while lower displays bring physical products into reach as visitors approach.",
      },
    ],
  },
  {
    id: "game-systems-preview",
    title: "Game Systems — Project Preview",
    shortTitle: "Game Systems",
    summary: "A temporary project page reserved for future game-development case studies.",
    primaryCategory: "game",
    discipline: "development",
    tags: ["game", "unity", "systems", "preview"],
    status: "placeholder",
    order: 4,
    thumbnail: placeholderMedia,
    cover: placeholderMedia,
    role: "Project preview",
    year: "Coming soon",
    tools: ["Details pending"],
    sections: [{ id: "game-preview", eyebrow: "01 / Preview", title: "Case study content is being prepared", copy: "The final project story, process and media will replace this temporary layout without changing the navigation structure." }],
  },
  {
    id: "web-experiences-preview",
    title: "Web Experiences — Project Preview",
    shortTitle: "Web Experiences",
    summary: "A temporary project page reserved for future web product and interface case studies.",
    primaryCategory: "web",
    discipline: "development",
    tags: ["web", "react", "interface", "preview"],
    status: "placeholder",
    order: 5,
    thumbnail: placeholderMedia,
    cover: placeholderMedia,
    role: "Project preview",
    year: "Coming soon",
    tools: ["Details pending"],
    sections: [{ id: "web-preview", eyebrow: "01 / Preview", title: "Case study content is being prepared", copy: "The final project story, process and media will replace this temporary layout without changing the navigation structure." }],
  },
  {
    id: "desktop-apps-preview",
    title: "Desktop Apps — Project Preview",
    shortTitle: "Desktop Apps",
    summary: "A temporary project page reserved for future desktop and mobile application case studies.",
    primaryCategory: "app",
    discipline: "development",
    tags: ["app", "desktop", "mobile", "automation", "preview"],
    status: "placeholder",
    order: 6,
    thumbnail: placeholderMedia,
    cover: placeholderMedia,
    role: "Project preview",
    year: "Coming soon",
    tools: ["Details pending"],
    sections: [{ id: "app-preview", eyebrow: "01 / Preview", title: "Case study content is being prepared", copy: "The final project story, process and media will replace this temporary layout without changing the navigation structure." }],
  },
];
